query FetchPosts($limit: Int!) {
  newPosts: posts(limit: $limit, order_by: { createdAt: desc }) {
    ...PostCard
  }
  trendPosts: posts(
    limit: $limit
    order_by: { likes_aggregate: { count: desc } }
  ) {
    ...PostCard
  }
}
