query SearchPosts($where: post_bool_exp!, $limit: Int!, $offset: Int!) {
  posts(
    where: $where
    limit: $limit
    offset: $offset
    order_by: { likes_aggregate: { count: desc } }
  ) {
    ...PostCard
  }
  postsAggregate(where: $where) {
    aggregate {
      count
    }
  }
}
