query FetchStockedPosts($userId: String!, $limit: Int!, $offset: Int!) {
  stocks(
    where: { userId: { _eq: $userId } }
    limit: $limit
    offset: $offset
    order_by: { createdAt: desc }
  ) {
    id
    post {
      id
      title
      content
      createdAt
      updatedAt
    }
  }
  stocksAggregate {
    aggregate {
      count
    }
  }
}
