query FetchNewPosts($limit: Int!, $offset: Int!) {
  posts(limit: $limit, offset: $offset, order_by: { createdAt: desc }) {
    ...PostCard
  }
  postsAggregate {
    aggregate {
      count
    }
  }
}
