query FetchPost($postId: Int!, $userId: String!, $isLoggedIn: Boolean = false) {
  post(id: $postId) {
    id
    title
    description
    content
    createdAt
    updatedAt
    user {
      id
      name
      picture
    }
    likes_aggregate {
      aggregate {
        sum {
          count
        }
      }
    }
    likes(where: { userId: { _eq: $userId } }, limit: 1)
      @include(if: $isLoggedIn) {
      id
      userId
      count
    }
    stocks @include(if: $isLoggedIn) {
      id
    }
    ...PostTags
  }
}
