query FetchPost($postId: Int!) {
  post(id: $postId) {
    id
    title
    description
    content
    createdAt
    updatedAt
    user {
      id
      name
      picture
    }
    likes {
      id
      user_id
      count
    }
    ...PostTags
  }
}
