query FetchPost($postId: Int!, $userId: String!, $isLoggedIn: Boolean = false) {
  post(id: $postId) {
    id
    title
    description
    content
    createdAt
    updatedAt
    user {
      id
      name
      picture
    }
    # NOTE: 空配列or要素が1つ
    likes(where: { userId: { _eq: $userId } }) @include(if: $isLoggedIn) {
      id
    }
    likes_aggregate {
      aggregate {
        count
      }
    }
    # NOTE: パーミッションの設定で自分のストックしか取得できないので空配列or要素が1つ
    stocks @include(if: $isLoggedIn) {
      id
    }
    ...PostTags
  }
}
